#pragma once

enum MAQUINA_ESTADOS {
    LISTO,
    INFORMACION_RECIBIDA,
    AVANZANDO,
    DECISION,
    GIRANDO_DER,
    GIRANDO_IZQ,
    GIRANDO_180,
    FRENANDO
};
/*
enum MAQUINA_NUEVA {
    LISTO,
    AVANZANDO,
    DECISION,
    PREGIRO_DER,
    PREGIRO_IZQ,
    POSTGIRO,
    GIRANDO_DER,
    GIRANDO_IZQ,
    GIRANDO_180,
}; */